---
# handlers file for application

- name: start application
  service:
    daemon_reload: yes
    name: "{{ service_name }}"
    state: started
    enabled: yes

- name: restart application
  service:
    name: "{{ service_name }}"
    state: restarted