---

- name: Create Application dir
  file:
    path: "{{ package_file_remote_location }}"
    state: directory

- name: Ensure group "spring" exists
  group:
    name: spring
    state: present

- name: Ensure user "spring" exists
  user:
    name: spring
    state: present

- name: Assigining the group
  command: chown -R spring:spring /usr/local/application
  ignore_errors: True

- name: Copy systemd service
  template:
    src: ../templates/sysService.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"

- name: Copy {{ package_file_name }} to {{ package_file_remote_location }}
  copy:
    src: "{{ package_file_location }}/{{ package_file_name }}"
    dest: "{{ package_file_remote_location }}"
  notify: start application

- name: Check if Service Exists
  stat:
    path: "/etc/systemd/system/{{ service_name }}.service"
  register: service_status

- name: Restart service
  command: /bin/true
  when: service_status.stat.exists
  notify: restart application